document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta name=\'description\' content=\'\'>");
document.writeln("    <meta name=\'author\' content=\'\'>");
document.writeln("    <title>DAI-19-October 13-15 2019, Beijing, China</title>");
document.writeln("	<!-- core CSS -->");
document.writeln("    <link href=\'../css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'../css/font-awesome.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'../css/animate.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'../css/main.css\' rel=\'stylesheet\'>");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("    <script src=\'../js/html5shiv.js\'></script>");
document.writeln("    <script src=\'../js/respond.min.js\'></script>");
document.writeln("    <![endif]--> ");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'../css/index.css\'>  ");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("    <footer class=\'py-5 bg-dark\'>");
document.writeln("      <div class=\'footer\'>");
document.writeln("        <p class=\'m-0 text-center text-white\'>Copyright 2023 Association for Distributed Artificial Intelligence, All Rights Reserved.</p>");
document.writeln("      </div>");
document.writeln("    </footer>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");