document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta name=\'description\' content=\'\'>");
document.writeln("    <meta name=\'author\' content=\'\'>");
document.writeln("    <title>DAI-22-December 15 to 17, 2022, Tianjin, China</title>");
document.writeln("	<!-- core CSS -->");
document.writeln("    <link href=\'../css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'../css/font-awesome.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'../css/animate.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'../css/main.css\' rel=\'stylesheet\'>");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("    <script src=\'../../js/html5shiv.js\'></script>");
document.writeln("    <script src=\'../../js/respond.min.js\'></script>");
document.writeln("    <![endif]--> ");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'../css/index.css\'>  ");
document.writeln("</head><!--/head-->");
document.writeln("");
document.writeln("<body>");
document.writeln("    <header id=\'header\'>");
document.writeln("        <nav id=\'main-menu\' class=\'navbar navbar-default navbar-fixed-top top-nav-collapse\' role=\'banner\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <div class=\'navbar-header\'>");
document.writeln("        <a class=\'return-but_21\' href=\'../../index.html\'><img src=\'../img/returnHome.png\'></a>");
document.writeln("                    <button type=\'button_21\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'.navbar-collapse\'>");
document.writeln("                        <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                        <span class=\'icon-bar\'></span>");
document.writeln("                        <span class=\'icon-bar\'></span>");
document.writeln("                        <span class=\'icon-bar\'></span>");
document.writeln("                    </button>");
document.writeln("                    <a href=\'index.html\' style=\' color: #ad1e25 !important;text-shadow: #4a463f 10px 10px 10px;\'>");
document.writeln("                        <img src=\'../../img/logo2022.png\' class=\'logo_21\'>");
document.writeln("                        <span class=\'hidden-xs hidden-sm hidden-md\'>DAI-23-Nov 30 to Dec 03, 2023, Singapore</span>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("				");
document.writeln("                <div class=\'collapse navbar-collapse navbar-right\'>");
document.writeln("                    <ul class=\'nav navbar-nav \'>");
document.writeln("                        <li><a href=\'index.html\'>Home</a></li>");
document.writeln("                        <li class=\'dropdown\'>");
document.writeln("                            <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                                Calls <b class=\'caret\'></b>");
document.writeln("                            </a>");
document.writeln("                            <ul class=\'dropdown-menu\'>");
document.writeln("                                <li><a href=\'important-dates.html\'>Important Dates</a></li>");
document.writeln("                                <li><a href=\'call-for-papers.html\'>Call for Papers</a></li>");
document.writeln("                                <li><a href=\'workshops.html\'>Call for Workshops/Tutorials</a></li>");
document.writeln("                                <li><a href=\'invited_paper.html\'>Call for Invited Papers</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'dropdown\'>");
document.writeln("                            <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                                Program <b class=\'caret\'></b>");
document.writeln("                            </a>");
document.writeln("                            <ul class=\'dropdown-menu\'>");
document.writeln("");
document.writeln("");
document.writeln("                                <li><a href=\'program-overview.html\'>Program Overview</a></li>");
// document.writeln("                                <li><a href=\'guidance.html\'>Presentation Guidance</a></li>");
// document.writeln("                                <li><a href=\'detailedprogram.html\'>Paper Presentation Program</a></li>");
document.writeln("                                <li><a href=\'./Program-Keynotes.html\'>Keynotes</a></li>");
document.writeln("                                <li><a href=\'./tutorials.html\'>Tutorials</a></li>");
// document.writeln("                                <li><a href=\'./tutorials2.html\'>Tutorial2</a></li>");
//document.writeln("                                <li><a href=\'javascript:void(0);\'>Tutorials</a></li>");
document.writeln("                                <li><a href=\'workshops.html>Workshops</a></li>");
document.writeln("                                <li><a href=\'./Sponsorship_Talk.html\'>Sponsorship Talks</a></li>");
document.writeln("                                <li><a href=\'./proceedings.html\'>Accepted Papers</a></li>");
document.writeln("                                <li><a href=\'./invited_papers.html\'>Invited Papers</a></li>");
// document.writeln("                                <li><a href=\'./poster-presentation.html\'>Poster Presentation</a></li>");
// document.writeln("                                <li><a href=\'http://drive-ml.com/competition/\'>Competition</a></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'dropdown\'>");
document.writeln("                            <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                                Committees <b class=\'caret\'></b>");
document.writeln("                            </a>");
document.writeln("                            <ul class=\'dropdown-menu\'>");
document.writeln("                                <li><a href=\'committees.html\'>Conference Committee</a></li>");
document.writeln("                                <li><a href=\'program-committees.html\'>Program Committee</a></li>");
document.writeln("");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'registration.html\'>Registration</a></li>");
document.writeln("                        <li><a href=\'sponsorship.html\'>Sponsorship</a></li>");
document.writeln("                        <li class=\'dropdown\'>");
document.writeln("                            <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                                Venue <b class=\'caret\'></b>");
document.writeln("                            </a>");
document.writeln("                            <ul class=\'dropdown-menu\'>");
document.writeln("                                <li><a href=\'venue.html\'>Conference Venue</a></li>");
document.writeln("                                <li><a href=\'hotel.html\'>Hotel Information</a></li>");
// document.writeln("                                <li><a href=\'Banquet.html\'>Banquet</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
// document.writeln("                        <li><a href=\'contact.html\'>Contact</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div><!--/.container-->");
document.writeln("        </nav><!--/nav-->");
document.writeln("    </header><!--/header-->");
document.writeln("</body>");
document.writeln("</html>");